package br.com.fiap.main;

import br.com.fiap.conexoes.ConexaoFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class TesteCriarTabelas {


    public static void main(String[] args) throws SQLException, ClassNotFoundException {
        Connection cn = new ConexaoFactory().conexao();


        String sql1 = "CREATE TABLE usuarios (" +
                "    id_usuario     NUMBER GENERATED BY DEFAULT AS IDENTITY," +
                "    nome             VARCHAR(80) NOT NULL," +
                "    email            VARCHAR(80) NOT NULL," +
                "    senha            VARCHAR(50) NOT NULL," +
                "    tipo_usuario     VARCHAR(20)," +
                "    data_cadastro    VARCHAR(20)," +
                "    CONSTRAINT usuarios_id_pk PRIMARY KEY (id_usuario)," +
                "    CONSTRAINT usuarios_email_uk UNIQUE (email))";
        PreparedStatement stmt1 = cn.prepareStatement(sql1);
        stmt1.execute();
        stmt1.close();

        String sql2 = "CREATE TABLE cursos (" +
                "    id_curso     NUMBER GENERATED BY DEFAULT AS IDENTITY," +
                "    titulos              VARCHAR(100) NOT NULL," +
                "    descricao            VARCHAR(255)," +
                "    carga_horaria        NUMBER(3)," +
                "    categoria            VARCHAR(50) NOT NULL," +
                "    nivel                VARCHAR(20)," +
                "    CONSTRAINT cursos_id_pk PRIMARY KEY (id_curso))" ;
        PreparedStatement stmt2 = cn.prepareStatement(sql2);
        stmt2.execute();
        stmt2.close();

        String sql3 = "CREATE TABLE empresas(" +
                "    id_empresa         NUMBER GENERATED BY DEFAULT AS IDENTITY," +
                "    nome_empresa          VARCHAR(100) NOT NULL," +
                "    cnpj            VARCHAR(20) NOT NULL," +
                "    setor      VARCHAR(50)," +
                "    tamanho      VARCHAR(10)," +
                "    CONSTRAINT empresas_id_pk PRIMARY KEY (id_empresa)," +
                "    CONSTRAINT empresas_cnpj_uk UNIQUE (cnpj))";
        PreparedStatement stmt3 = cn.prepareStatement(sql3);
        stmt3.execute();
        stmt3.close();

        String sql4 = "CREATE TABLE vagas (" +
                "    id_vaga                 NUMBER GENERATED BY DEFAULT AS IDENTITY," +
                "    id_empresa              NUMBER NOT NULL," +
                "    titulo_vaga             VARCHAR(150) NOT NULL," +
                "    descricao               VARCHAR(255)," +
                "    competencias_requeridas VARCHAR(255)," +
                "    nivel_experiencia       VARCHAR(50)," +
                "    CONSTRAINT vagas_id_pk PRIMARY KEY (id_vaga)," +
                "    CONSTRAINT vagas_empresas_fk FOREIGN KEY (id_empresa)" +
                "        REFERENCES empresas (id_empresa))";
        PreparedStatement stmt4 = cn.prepareStatement(sql4);
        stmt4.execute();
        stmt4.close();

        String sql5 = "CREATE TABLE inscricoes (" +
                "    id_inscricao      NUMBER GENERATED BY DEFAULT AS IDENTITY," +
                "    id_usuario        NUMBER NOT NULL," +
                "    id_curso          NUMBER NOT NULL," +
                "    descricao         VARCHAR(255)," +
                "    data_inscricao    VARCHAR(20)," +
                "    status            VARCHAR(20) NOT NULL," +
                "    CONSTRAINT inscricoes_id_pk PRIMARY KEY (id_inscricao)," +
                "    CONSTRAINT inscricoes_usuarios_fk FOREIGN KEY (id_usuario)" +
                "        REFERENCES usuarios(id_usuario)," +
                "    CONSTRAINT inscricoes_cursos_fk FOREIGN KEY (id_curso)" +
                "        REFERENCES cursos(id_curso)," +
                "    CONSTRAINT inscricoes_status_ck CHECK (status IN('ativo','concluido','cancelado')))";

        PreparedStatement stmt5 = cn.prepareStatement(sql5);
        stmt5.execute();
        stmt5.close();

        System.out.println("Tabelas criadas com sucesso!");
        cn.close();
    }


}
